[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@account-abstraction@v0.7.0/=lib/account-abstraction/contracts/",
]
solc = "0.8.24"

# Optimizer settings
optimizer = true
optimizer_runs = 200

# Network settings for deployment
[rpc_endpoints]
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"

[etherscan]
base_sepolia = { key = "${BASESCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
